concurrent = 1
check_interval = 0
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "docker"
  url = "http://192.168.8.4:8800"
  id = 8
  token = "glrt-V1NNXsfNnc63kmxbhbzY"
  token_obtained_at = 2023-12-12T14:41:59Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "shell"
  [runners.cache]
    MaxUploadedArchiveSize = 0
