services:
  webserver-db:
    image: mysql:5.7.38-debian
    container_name: webserver-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - .env
    volumes:
      - ./database:/var/lib/mysql
    command: --sql_mode=""
  webserver-http:
    image: webdevops/php-apache:alpine-php7
    container_name: webserver-http
    expose:
      - "80"
    volumes:
      - ./www/site:/app
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: webserver-phpmyadmin
    env_file:
      - .env
    expose:
      - "80"
  webserver-nginx:
    container_name: acc-nginx
    restart: unless-stopped
    image: nginx
    ports:
        - 80:80
        - 443:443
    volumes:
        - ../proxy/default.conf:/etc/nginx/nginx.conf
        - ../proxy/includes/proxy.conf:/etc/nginx/includes/proxy.conf



