- hosts: all
  become: true
  tasks:
    - name: Installing NRPE Server
      apt:
        name: nagios-nrpe-server
        state: latest
        update_cache: true
    - name: Installing Nagios Plugins
      apt:
        name: nagios-nrpe-plugin
        state: latest
        update_cache: false
    - name: Changing nagios host
      lineinfile: 
        path: /etc/nagios/nrpe.cfg
        regexp: '^(.*)allowed_hosts=(.*)$' 
        line: 'allowed_hosts=127.0.0.1,{{ external_ip }}'
        backrefs: yes
    - name: Add memory plugin to nrpe
      lineinfile:
        path: /etc/nagios/nrpe.cfg
        line: 'command[check_mem]=/usr/lib/nagios/plugins/check_mem.sh  -w 80 -c 90'
        insertafter: check_zombie_procs.*
    - name: Download memory plugin
      ansible.builtin.copy:
        src: ../Plugins/check_mem.sh  
        dest: /usr/lib/nagios/plugins/check_mem.sh
        mode: '0777'
    - name: Start NRPE Service
      ansible.builtin.service:
        name: nagios-nrpe-server 
        state: reloaded
